### PR TITLE
7x7 MBL points with less interference

### PR DESCRIPTION
**Pull request by 3d-gussner**
Hi Pavel, first thanks for the pull and improvement of the 7x7 MBL.
I tried to understand your concerns about the magnets interference to the PINDA readings. I think i found a pattern where the probe points aren't too close to the magnets.
- If the 1st MBL probe point starts at x6 y24 (nozzle is x1 y1) and then with a spacing of 34mm in both directions the back right point will be at x228 y210 (nozzle x205 y205).
- Only 5 probe points will overlap the magnet cutouts.
  - Probe point x126 y74 has a ~2mm overlapping to the cutout
  - Probe point x126 y142 has a ~1.5 mm overlapping to the cutout
  - Probe point x160 y108 has a ~0.5 mm overlapping to the cutout
  - Probe point x92 y108 has a ~0.25 mm overlapping to the cutout
  - Probe point x58 y108 has a ~0.25 mm overlapping to the cutout

As the magnets are square, just at 2 probe points could interfere/overlap magnets.
- Probe point x126 y74
- Probe point x126 y142

7x7 mbl points
Here a link to it my Fusion attempt to find optimal MBL probe points https://a360.co/2TrpuLp

### CODE REVIEW

**Comment by crzcrz** [comment]
We've been exploring the issue of magnets influencing the PINDA triggering height on 602 Discord, and have some results to share.

Below is the 100x100 height map captured with Klipper.

output

As you can see the magnets clearly show.

Now with some common mesh sizes:

output_3x3

The default 3x3 seems inadequate - 2 points out of 9 hit magnets.

output_4x4

output_5x5

output_6x6

output_7x7

Looks like 4x4 is reasonable.

And finally a couple rows in isolation, to see the magnitude of the error introduced by magnets:

unknown

I hope you find this interesting.

**Comment by gregsaun** [comment]
@3d-gussner @crzcrz beautiful work guys.

As we discussed on the Discord, we have to take into account the standoffs as well, not only the magnets.  Due to thermal expansion, the heated bed will skew between the standoffs because they are "fixed/constrained". So we should probe on the standoffs and between them and at the same time avoid the magnets.

@3d-gussner I designed the bed like you and I am having a slightly different coordinate than you. I have defined the zero on the bed by exporting layers from KiCad on SVG.

levelling_02

**Comment by matthew-humphrey** [comment]
I think if I implement this for Marlin, I will create a #define macro that supports a completely custom set of points. Then we can do a regular grid with just a few points adjusted to avoid magnets. With a 5x5 or higher, I don't see any value to be gained by making points fall exactly on standoffs. But with the macro, people can adjust that if they disagree.

**Comment by gregsaun** [comment]
@matthew-humphrey standoffs will be reference of height and in between will happen the skew to thermal expansion. Keeping them will help to adjust the standoffs height with alternative manual leveling methods.

**Comment by stahlfabrik** [comment]
@matthew-humphrey 
Ah so you would replace a mesh point with measurement that has been taken nearby - but away from the magnet? And the rest of the measurements would take place at the normal location on the mesh?

I also like the Prusa idea, of taking the average of the neighbouring points, if those are not also over a magnet. They define a bitmap (of 0s and 1s) to define which point is over a magnet, and which one is not)

I still think and hope that regular 4x6 MBL is the prefect way to go - as it would not require any implementation.

**Comment by matthew-humphrey** [comment]
No, the mesh point position would be adjusted as well for mesh calculation, not just where the point is measured. Anyway, the benefit of this approach is that it accommodates both people like gregoire that want the mesh aligned exactly over the standoffs, versus people like me who think at 7x7 it doesn't  matter. Just update the macro defined function in the config file.

**Comment by 3d-gussner** [comment]
@gregsaun I imported the bed cutouts , mk52 and spring steel sheet into Fusion360 to find the 0,0 point it may not be 100% accurate but should be quite close.

**Comment by matthew-humphrey** [comment]
BTW @gregsaun, you can see the shaded area above is where the probe can reach. The orange points are the standoff/screw locations. So only some of those are within the area that can be probed.

**Comment by 3d-gussner** [comment]
Maybe it makes more sense to move all comments to the Prusa3d github, as @PavelSindler didn't see this one in 1st place...
I will close it within 5 days or so.
@gregsaun @crzcrz @matthew-humphrey @stahlfabrik please move your comments there. I think that work shouldn't just disappear as many thoughts got into it.

I suggest https://github.com/prusa3d/Prusa-Firmware/pull/1607 or open a new issue

**Comment by PavelSindler** [comment]
I have just read it. It is interesting. Thanks. I would like to polish current 7x7 mesh bed leveling first. Some people reported crash detections, other higher Z-leveling occurence.

**Comment by sgoll** [comment]
@3d-gussner You closed this PR. Have your suggestions been implemented in the upstream Prusa firmware repository?

**Comment by 3d-gussner** [comment]
@sgoll yes the first suggestion made it. The last is still open to discuss

**Pull request closed without merging**
